/**
 * Export a processed document as a printable page.
 *
 * This opens a clean, print-styled window and triggers the browser's print
 * dialog, where the user can choose "Save as PDF". Doing it this way keeps
 * Tibetan Unicode rendering intact and avoids pulling in a PDF library.
 */

function escapeHtml(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function paragraphs(text, className = "") {
  if (!text?.trim()) return `<p class="empty">Not available.</p>`;
  return text
    .trim()
    .split(/\n{2,}/)
    .map((p) => `<p class="${className}">${escapeHtml(p)}</p>`)
    .join("");
}

export function buildExportHtml(doc) {
  const keywords = Array.isArray(doc.keywords) ? doc.keywords : [];

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(doc.fileName || "Document")}</title>
  <link
    href="https://fonts.googleapis.com/css2?family=Noto+Serif+Tibetan:wght@400;600&display=swap"
    rel="stylesheet"
  />
  <style>
    @page { margin: 20mm; }
    * { box-sizing: border-box; }
    body {
      font-family: Georgia, "Times New Roman", serif;
      color: #1a1a1a;
      line-height: 1.6;
      max-width: 46rem;
      margin: 0 auto;
      padding: 2rem 1rem;
    }
    h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
    h2 {
      font-size: 1rem;
      text-transform: uppercase;
      letter-spacing: .08em;
      color: #555;
      border-bottom: 1px solid #ddd;
      padding-bottom: .35rem;
      margin: 2.25rem 0 1rem;
    }
    .meta { color: #666; font-size: .8rem; margin-bottom: 1.5rem; }
    .meta span + span::before { content: " · "; }
    .tibetan {
      font-family: "Noto Serif Tibetan", Georgia, serif;
      font-size: 1.25rem;
      line-height: 2.1;
    }
    .empty { color: #999; font-style: italic; }
    ul.keywords { list-style: none; padding: 0; }
    ul.keywords li {
      display: inline-block;
      border: 1px solid #ddd;
      border-radius: .4rem;
      padding: .25rem .6rem;
      margin: 0 .35rem .35rem 0;
      font-size: .8rem;
    }
    ul.keywords .gloss { color: #666; }
    footer {
      margin-top: 3rem;
      border-top: 1px solid #ddd;
      padding-top: .75rem;
      font-size: .7rem;
      color: #888;
    }
    section { page-break-inside: avoid; }
  </style>
</head>
<body>
  <h1>${escapeHtml(doc.fileName || "Untitled document")}</h1>
  <div class="meta">
    ${doc.pages ? `<span>${doc.pages} page(s)</span>` : ""}
    ${doc.wordCount ? `<span>${doc.wordCount.toLocaleString()} words</span>` : ""}
    ${typeof doc.ocrConfidence === "number" ? `<span>${doc.ocrConfidence}% OCR confidence</span>` : ""}
    ${doc.language ? `<span>${escapeHtml(doc.language)}</span>` : ""}
  </div>

  <section>
    <h2>Original Text</h2>
    ${paragraphs(doc.originalText, "tibetan")}
  </section>

  <section>
    <h2>English Translation</h2>
    ${paragraphs(doc.translation)}
  </section>

  <section>
    <h2>AI Summary</h2>
    ${paragraphs(doc.summary)}
  </section>

  <section>
    <h2>Keywords</h2>
    ${
      keywords.length
        ? `<ul class="keywords">${keywords
            .map(
              (k) =>
                `<li><strong>${escapeHtml(k.term)}</strong>${
                  k.translation ? ` — <span class="gloss">${escapeHtml(k.translation)}</span>` : ""
                }</li>`
            )
            .join("")}</ul>`
        : `<p class="empty">Not available.</p>`
    }
  </section>

  <footer>
    Generated by the Tibetan Research Assistant on ${new Date().toLocaleString()}.
    Machine-generated OCR, translation and summary — verify before citing.
  </footer>
</body>
</html>`;
}

export function exportDocument(doc) {
  if (!doc) return;

  const win = window.open("", "_blank", "width=900,height=1000");
  if (!win) {
    alert("Please allow pop-ups for this site to export your document.");
    return;
  }

  win.document.write(buildExportHtml(doc));
  win.document.close();

  // Give fonts a moment to load before opening the print dialog.
  win.onload = () => setTimeout(() => win.focus() || win.print(), 400);
}
